export const seedProducts = [
  {
    "id": "prod_1",
    "code": "15041002",
    "name_ar": "مريلة زي موحد دانكن",
    "name_en": "UNIFORM.APRON DD",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_2",
    "code": "10123003",
    "name_ar": "ساندوتش بيغل قرفة دانكن (1 × 60 حبة)",
    "name_en": "SANDWICH.DD BAGEL CINNAMON (1X60 PCS)",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_3",
    "code": "10123002",
    "name_ar": "ساندوتش بيغل حبوب متعددة دانكن (1 × 60 حبة)",
    "name_en": "SANDWICH.DD BAGEL MULTIGRAIN (1X60 PCS)",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_4",
    "code": "10123001",
    "name_ar": "ساندوتش بيغل سادة دانكن (1 × 60 حبة)",
    "name_en": "SANDWICH.DD BAGEL PLAIN (1X60 PCS)",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_5",
    "code": "14011004",
    "name_ar": "مجرفة أتربة طويلة مع فرشاة",
    "name_en": "DISPOSABLES.LONG DUST PAN WITH BRUSH",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_6",
    "code": "14011001",
    "name_ar": "مكنسة بلاستيك ناعمة",
    "name_en": "DISPOSABLES.SOFT PLASTIC BROOM",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_7",
    "code": "14011007",
    "name_ar": "مجرفة أتربة إيكولاب",
    "name_en": "ECOLAB. DUSTPAN",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_8",
    "code": "14011006",
    "name_ar": "مساحة أرضيات حمراء إيكولاب",
    "name_en": "ECOLAB. FLOOR SQUEEGEE RED",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_9",
    "code": "12023003",
    "name_ar": "مافن التفاح",
    "name_en": "APPLE MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_10",
    "code": "12023008",
    "name_ar": "مافن التوت الأزرق",
    "name_en": "BLUEBERRY MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_11",
    "code": "12023001",
    "name_ar": "مافن التوت الأزرق (جاهز)",
    "name_en": "BLUEBERRY MUFFIN FG",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_12",
    "code": "12023004",
    "name_ar": "كيك الشوكولاتة",
    "name_en": "CHOCOLATE CAKE",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_13",
    "code": "12023024",
    "name_ar": "كوكيز بقطع الشوكولاتة",
    "name_en": "CHOCOLATE CHIP COOKIES",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_14",
    "code": "12023007",
    "name_ar": "مافن الشوكولاتة",
    "name_en": "CHOCOLATE MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_15",
    "code": "12023002",
    "name_ar": "مافن الشوكولاتة (جاهز)",
    "name_en": "CHOCOLATE MUFFIN FG",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_16",
    "code": "12023018",
    "name_ar": "مافن التمر",
    "name_en": "DATE MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_17",
    "code": "12023023",
    "name_ar": "كيك التمر",
    "name_en": "DATES CAKE",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_18",
    "code": "12023022",
    "name_ar": "مافن التمر",
    "name_en": "DATES MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_19",
    "code": "12023006",
    "name_ar": "كوكيز دبل شوكولاتة",
    "name_en": "DOUBLE CHOCO COOKIES",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_20",
    "code": "12023005",
    "name_ar": "كيك رخامي (ماربل)",
    "name_en": "MARBLE CAKE",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_21",
    "code": "12023021",
    "name_ar": "كيك الفانيليا",
    "name_en": "VANILLA CAKE",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_22",
    "code": "12023019",
    "name_ar": "مافن فانيليا بالشوكولاتة",
    "name_en": "VANILLA CHOCO MUFFIN",
    "category": "كيك وكوكيز ومافن",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_23",
    "code": "10015003",
    "name_ar": "كبسولات قهوة إسبريسو بولد روست (10 كبسولات)",
    "name_en": "COFFEE.BOLD ROAST ESPRESSO (10CAPS)",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_24",
    "code": "10015001",
    "name_ar": "كبسولات قهوة إسبريسو سيجنتشر بلند (10 كبسولات)",
    "name_en": "COFFEE.SIGNATURE BLEND ESPRESSO (10CAPS)",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_25",
    "code": "10022001",
    "name_ar": "شرائح جبن للساندوتش (10 شرائح)",
    "name_en": "CHEESE.SLICE CHEESE FOR SANDWICH (10 SLICES)",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_26",
    "code": "10022023",
    "name_ar": "جبنة كريمية (2 كجم)",
    "name_en": "CREAM CHEESE (2KG)",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_27",
    "code": "10022003",
    "name_ar": "لبنة كاملة الدسم (180 جم × 60 حبة)",
    "name_en": "SPREADS.LABNEH FULL FAT (180 GMS 60 PCS)",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_28",
    "code": "10022002",
    "name_ar": "جبنة كريمية فيلادلفيا 180 جم",
    "name_en": "SPREADS.PHILADELPHIA CREAM CHEESE 180 GM",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_29",
    "code": "10033008",
    "name_ar": "كريمة خفق بخاخ 250 مل",
    "name_en": "TOPPING.WHIPPING CREAM SPRAY 250 ML",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_30",
    "code": "13015001",
    "name_ar": "حامل أكواب كرتون ثنائي (2 كوب)",
    "name_en": "BOXES.TWO CUP CARRIER BOX",
    "category": "أغلفة وحوامل الأكواب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_31",
    "code": "13015004",
    "name_ar": "حامل أكواب رباعي (4 أكواب)",
    "name_en": "CUPS.CARRIER 4 CUPS (1X 200 PCS)",
    "category": "أغلفة وحوامل الأكواب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_32",
    "code": "13015006",
    "name_ar": "أغلفة ورقية عازلة للأكواب 14 و16 و20 أونصة",
    "name_en": "DISPOSABLES SLEEVE FOR 14 16 20OZ CUPS",
    "category": "أغلفة وحوامل الأكواب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_33",
    "code": "13015005",
    "name_ar": "أغلفة ورقية عازلة للأكواب 9 و10 أونصة",
    "name_en": "DISPOSABLES SLEEVE FOR 9 10 OZ CUPS",
    "category": "أغلفة وحوامل الأكواب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_34",
    "code": "13024001",
    "name_ar": "ملاعق بلاستيكية (مغلف 1 × 50 حبة)",
    "name_en": "DISPOSABLES.PLASTIC SPOON PACK (1X50 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_35",
    "code": "10012001",
    "name_ar": "قهوة دانكن دارك روست مطحونة (كيس 1 رطل)",
    "name_en": "COFFEE.DD DARK ROAST GROUNDS BAG 01 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_36",
    "code": "10014001",
    "name_ar": "قهوة دانكن خالية من الكافيين مطحونة (كيس 1 رطل)",
    "name_en": "COFFEE.DD DECAF COFFEE GROUNDS BAG 01 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_37",
    "code": "10013001",
    "name_ar": "حبوب قهوة إسبريسو (كيس 1 كجم)",
    "name_en": "COFFEE.ESPRESSO BEANS BAG 01 KG",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_38",
    "code": "12012010",
    "name_ar": "دونات بيري تروبيكس",
    "name_en": "BERRY TROPIX",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_39",
    "code": "12012022",
    "name_ar": "دونات شوكو هارت (قلب الشوكولاتة)",
    "name_en": "CHOCO HEART",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_40",
    "code": "12012024",
    "name_ar": "دونات كراون كنافة بالشوكولاتة",
    "name_en": "CHOCO KUNAFA CROWN",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_41",
    "code": "12012007",
    "name_ar": "دونات كوفي رول",
    "name_en": "COFFEE ROLL",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_42",
    "code": "12012011",
    "name_ar": "علبة كوكيز",
    "name_en": "COOKIE BOX",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_43",
    "code": "12012023",
    "name_ar": "دونات دارك ويف بالفستق",
    "name_en": "DARKWAVE PISTACHIO",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_44",
    "code": "12012019",
    "name_ar": "دونات هارموني تمر بالبندق",
    "name_en": "HAZELNUT DATES HARMONY",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_45",
    "code": "12012018",
    "name_ar": "دونات هارموني تمر بالبندق مخصصة",
    "name_en": "HAZELNUT DATES HARMONY DONUT",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_46",
    "code": "12012012",
    "name_ar": "دونات مانجو ميراج",
    "name_en": "MANGO MIRAGE",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_47",
    "code": "12012013",
    "name_ar": "دونات أوريو هازلنوفا",
    "name_en": "OREO HAZENOVA",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_48",
    "code": "12012021",
    "name_ar": "دونات بستاشيو كريمي كرانش",
    "name_en": "PISTACHIO CREAMY CRUNCH",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_49",
    "code": "12012025",
    "name_ar": "دونات روبي كرانش",
    "name_en": "RUBY CRUNCH",
    "category": "دونات فانسى ومميز",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_50",
    "code": "13019001",
    "name_ar": "فلاتر قهوة كولد برو",
    "name_en": "DISPOSABLES.COLD BREW FILTER",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_51",
    "code": "10083012",
    "name_ar": "شراب (سيروب) بلو باي 1 لتر",
    "name_en": "BLUE BAY SYRUP (6 X1 LTR)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_52",
    "code": "10083052",
    "name_ar": "صوص كراميل في عبوة قلم 300 مل",
    "name_en": "CARAMEL SAUCE PEN 300 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_53",
    "code": "10083025",
    "name_ar": "بودرة ماتشا 1 كجم",
    "name_en": "MATCHA POWDER -1KG",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_54",
    "code": "10083044",
    "name_ar": "بودرة ماتشا جست تشيل 1 كجم",
    "name_en": "MATCHA POWDER JUST CHILL (1KGX12 PCS)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_55",
    "code": "10083014",
    "name_ar": "بودرة شوكولاتة ساخنة (كيس 3 أرطال / 1.36 كجم)",
    "name_en": "POWDER.CHOCOLATE HOT POWDER BAG 03 LBS",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_56",
    "code": "10083013",
    "name_ar": "مسحوق فرابيه تشيزكيك 1 كجم",
    "name_en": "POWDER.FRAPPE-CHEESECAKE 1 KG",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_57",
    "code": "10083009",
    "name_ar": "صوص كراميل قلم 165 مل",
    "name_en": "SYRUP.CARAMEL SAUCE PEN 165 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_58",
    "code": "10083003",
    "name_ar": "شراب (سيروب) كراميل 750 مل",
    "name_en": "SYRUP.CARAMEL SYRUP 750 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_59",
    "code": "10083043",
    "name_ar": "شراب دا فينشي فراولة 750 مل",
    "name_en": "SYRUP.DAVINCI STRAWBERRY SYRUP (12 X 750ML)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_60",
    "code": "10083007",
    "name_ar": "شراب (سيروب) بندق 750 مل",
    "name_en": "SYRUP.HAZELNUT SYRUP 750 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_61",
    "code": "10083008",
    "name_ar": "صوص موكا قلم 165 مل",
    "name_en": "SYRUP.MOCHA SAUCE PEN 165 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_62",
    "code": "10083017",
    "name_ar": "شراب مونين توت أزرق 1 لتر",
    "name_en": "SYRUP.MONIN BLUEBERRY SYRUP (6X1LTR)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_63",
    "code": "10083004",
    "name_ar": "شراب مونين خوخ آيس تي 1 لتر",
    "name_en": "SYRUP.MONIN PEACH ICETEA SYRUP 01 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_64",
    "code": "10083005",
    "name_ar": "شراب مونين رانشو ليمونادة 1 لتر",
    "name_en": "SYRUP.MONIN RANCHO LEMONADE SYRUP 01 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_65",
    "code": "10083010",
    "name_ar": "شراب مونين فراولة 1 لتر",
    "name_en": "SYRUP.MONIN STRAWBERRY SYRUP 01 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_66",
    "code": "10083006",
    "name_ar": "شراب (سيروب) فانيليا 750 مل",
    "name_en": "SYRUP.VANILLA SYRUP 750 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_67",
    "code": "12021002",
    "name_ar": "كرواسون بالجبن",
    "name_en": "CHEESE CROISSANT",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_68",
    "code": "12021004",
    "name_ar": "كرواسون بالشوكولاتة",
    "name_en": "CHOCOLATE CROISSANT",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_69",
    "code": "12021006",
    "name_ar": "كرواسون ميبل بيكان",
    "name_en": "MAPLE PECAN CROISSANT",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_70",
    "code": "12021001",
    "name_ar": "كرواسون سادة",
    "name_en": "PLAIN CROISSANT",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_71",
    "code": "12021003",
    "name_ar": "كرواسون بالزعتر",
    "name_en": "ZAATER CROISSANT",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_72",
    "code": "10082004",
    "name_ar": "بيوريه مانجو ودراجون فروت 1 لتر",
    "name_en": "MANGO DRAGON FRUIT PUREE (6 X1 LTR)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_73",
    "code": "10082002",
    "name_ar": "بيوريه التوت الأزرق 1 لتر",
    "name_en": "SYRUP.BLUEBERRY PUREE 01 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_74",
    "code": "10082001",
    "name_ar": "بيوريه الكرز 1 لتر",
    "name_en": "SYRUP.CHERRY PUREE 01 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_75",
    "code": "12033005",
    "name_ar": "زبادي جرانولا بالعسل (1 × 36 × 170 جم)",
    "name_en": "HONEY GRANULA YOGHURT 1X36X170G",
    "category": "وجبات خفيفة ومكسرات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_76",
    "code": "12033002",
    "name_ar": "مكسرات بالكراميل (6 × 12 × 50 جم)",
    "name_en": "MERCHANDISE.CARAMEL NUT 6X12X50G",
    "category": "وجبات خفيفة ومكسرات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_77",
    "code": "12033001",
    "name_ar": "مكسرات بالشوكولاتة الداكنة (6 × 12 × 50 جم)",
    "name_en": "MERCHANDISE.DOUBLE DARK CHOC NUT 6X12X50G",
    "category": "وجبات خفيفة ومكسرات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_78",
    "code": "14027026",
    "name_ar": "مناديل ورقية 30×30 سم (1 × 4000 حبة)",
    "name_en": "DISPOSABLES NAPKINS GF SIZE 30X30 CM 1X4000",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_79",
    "code": "14027003",
    "name_ar": "قفازات استخدام واحد (مغلف 500 حبة)",
    "name_en": "DISPOSABLES.D. GLOVES 1 PACK",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_80",
    "code": "14027006",
    "name_ar": "كمامات وجه اقتصادية (مغلف 50 حبة)",
    "name_en": "DISPOSABLES.ECONOMY FACE MASK 1 PACK",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_81",
    "code": "14027008",
    "name_ar": "مناديل رول جامبو أزرق",
    "name_en": "DISPOSABLES.JUMBO ROLL-BLUE",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_82",
    "code": "14027007",
    "name_ar": "مناديل رول ماكسي",
    "name_en": "DISPOSABLES.MAXI ROLL",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_83",
    "code": "14027005",
    "name_ar": "غطاء رأس شبكي للشعر (مغلف 100 حبة)",
    "name_en": "DISPOSABLES.MOB CAP 1 PACK",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_84",
    "code": "14027002",
    "name_ar": "مناديل دانكن ورقية (1 × 3600 حبة)",
    "name_en": "DISPOSABLES.NAPKINS DD (1X3600)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_85",
    "code": "14027009",
    "name_ar": "أكياس نفايات سوداء (كرتون 300 حبة)",
    "name_en": "DISPOSABLES.TRASH BAG BLACK",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_86",
    "code": "12043002",
    "name_ar": "عصير كرز 300 مل",
    "name_en": "CHERRY JUICE 300ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_87",
    "code": "12043004",
    "name_ar": "عصير مانجو 300 مل",
    "name_en": "MANGO JUICE 300ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_88",
    "code": "12043003",
    "name_ar": "عصير برتقال 300 مل",
    "name_en": "ORANGE JUICE 300 ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_89",
    "code": "13022001",
    "name_ar": "أغطية أكواب قهوة وشاي 10 أونصة",
    "name_en": "LIDS COFFEE AND TEA CUPS LIDS 10OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_90",
    "code": "13022002",
    "name_ar": "أغطية أكواب قهوة 14 و16 و20 أونصة",
    "name_en": "LIDS COFFEE CUPS LIDS 14 16 20OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_91",
    "code": "13022007",
    "name_ar": "أغطية أكواب قهوة وشاي مزدوجة الجدار 10 أونصة",
    "name_en": "LIDS DW COFFEE AND TEA CUPS 10OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_92",
    "code": "13022008",
    "name_ar": "أغطية أكواب قهوة وشاي مزدوجة الجدار 14 و16 و20 أونصة",
    "name_en": "LIDS DW COFFEE AND TEA CUPS 14OZ 16OZ 20OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_93",
    "code": "13022010",
    "name_ar": "أغطية أكواب قهوة وشاي مزدوجة الجدار 9 أونصة",
    "name_en": "LIDS DW COFFEE AND TEA CUPS 9OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_94",
    "code": "13022004",
    "name_ar": "أغطية بلاستيكية مقببة (دوم) 12 و16 و24 أونصة",
    "name_en": "LIDS PLASTIC DOME LIDS 12 16 24OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_95",
    "code": "13022005",
    "name_ar": "أغطية بلاستيكية مسطحة (فلات) 12 و16 و24 أونصة",
    "name_en": "LIDS PLASTIC FLAT LIDS 12 16 24OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_96",
    "code": "13022003",
    "name_ar": "أغطية أكواب قهوة 9 أونصة",
    "name_en": "LIDS.COFFEE CUPS LIDS 9OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_97",
    "code": "13022011",
    "name_ar": "أغطية بلاستيكية مقببة (دوم) 32 أونصة",
    "name_en": "LIDS.PLASTIC DOME LIDS 32OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_98",
    "code": "13022009",
    "name_ar": "أغطية بلاستيكية مسطحة (فلات) 32 أونصة",
    "name_en": "LIDS.PLASTIC FLAT LIDS 32OZ",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_99",
    "code": "13022028",
    "name_ar": "أغطية علب الصوص 2 أونصة (20 مغلف × 100 حبة)",
    "name_en": "SAUCE LID 2 OZ 20 PACK X 100 PCS",
    "category": "أغطية الأكواب",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_100",
    "code": "13017007",
    "name_ar": "فلاتر تحضير القهوة الكبيرة (500 حبة)",
    "name_en": "DISPOSABLES.BULK BREWER FILTERS 1 PACK (500 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_101",
    "code": "13017006",
    "name_ar": "فلاتر قهوة (500 حبة)",
    "name_en": "DISPOSABLES.COFFEE FILTERS 1 PACK (500 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_102",
    "code": "13017008",
    "name_ar": "ورق تغليف غير مشمع (1 × 2000 حبة)",
    "name_en": "DISPOSABLES.UNWAX TISSUES (1X2000 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_103",
    "code": "13017002",
    "name_ar": "ورق مانع للزيوت أسود (1 × 1000 حبة)",
    "name_en": "GREASE PROOF BLACK LINER (BDL 1X1000 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_104",
    "code": "13017003",
    "name_ar": "ورق بارشمنت للخبز 12 × 10.75 (1 × 400 حبة)",
    "name_en": "PAPER PARCHMENT LINER 12 X 1075 1X400 PCS",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_105",
    "code": "10021001",
    "name_ar": "حليب كامل الدسم 1 لتر",
    "name_en": "MILK.FULL FAT MILK 01 LTR",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_106",
    "code": "10021002",
    "name_ar": "حليب قليل الدسم 1 لتر",
    "name_en": "MILK.LOW FAT MILK 01 LTR",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_107",
    "code": "10024001",
    "name_ar": "مشروب حليب اللوز الأصلي 8 × 1 لتر",
    "name_en": "MILK ALMOND DRINK ORIGINAL 8X1LTR",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_108",
    "code": "10024002",
    "name_ar": "مشروب حليب جوز الهند الأصلي 12 × 1 لتر",
    "name_en": "MILK COCONUT DRINK ORIGINAL 12X1LTR",
    "category": "أجبان وألبان",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_109",
    "code": "10151001",
    "name_ar": "مياه صودا فوارة 24 × 300 مل",
    "name_en": "SPARKLING SODA 24X300ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_110",
    "code": "10151003",
    "name_ar": "مياه صودا فوارة 30 × 250 مل",
    "name_en": "SPARKLING SODA 30X250ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_111",
    "code": "14013001",
    "name_ar": "رأس ممسحة أرضيات (كرتون 36 حبة)",
    "name_en": "DISPOSABLES.MOPHEAD (1 CTNX36PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_112",
    "code": "14013003",
    "name_ar": "رأس ممسحة أصفر إيكولاب",
    "name_en": "ECOLAB. MOP HEAD YELLOW",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_113",
    "code": "12013001",
    "name_ar": "مونشكين بافاريان",
    "name_en": "BAVARIAN MUNCHKIN",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_114",
    "code": "12013005",
    "name_ar": "مونشكين كيك بترنت",
    "name_en": "CAKE BUTTERNUT MUNCHKINS",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_115",
    "code": "12013007",
    "name_ar": "مونشكين شوكولاتة جليزد",
    "name_en": "CHOCO GLAZED MUNCHKIN",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_116",
    "code": "12013011",
    "name_ar": "مونشكين كيك جليزد",
    "name_en": "GLAZED CAKE MUNCHKINS",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_117",
    "code": "12013002",
    "name_ar": "مونشكين جليزد مخمر",
    "name_en": "GLAZED YEAST MUNCHKIN",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_118",
    "code": "16021005",
    "name_ar": "رول ورق حراري لشبكة مدى (1 × 100 رول)",
    "name_en": "PAPER.MADA THERMAL ROLL (1X100 PCS)",
    "category": "قرطاسية وملصقات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_119",
    "code": "16021004",
    "name_ar": "رول ورق طابعة الفواتير حراري (5 حبات)",
    "name_en": "PAPER.RECEIPT PRINTER ROLLS THERMO",
    "category": "قرطاسية وملصقات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_120",
    "code": "16021010",
    "name_ar": "رول ملصقات توصيل دانكن",
    "name_en": "STATIONARY.DUNKIN DELIVERY STICKERS ROLL",
    "category": "قرطاسية وملصقات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_121",
    "code": "16021008",
    "name_ar": "رول ملصقات مدة الصلاحية (1 × 1000)",
    "name_en": "STATIONARY.SHELF LIFE STICKERS ROLL (1X1000)",
    "category": "قرطاسية وملصقات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_122",
    "code": "10011004",
    "name_ar": "حبوب قهوة دانكن (كيس 2.5 رطل)",
    "name_en": "COFFEE.DD COFFEE BEANS BAG 2.5 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_123",
    "code": "10011001",
    "name_ar": "حبوب قهوة دانكن (كيس 5 أرطال)",
    "name_en": "COFFEE.DD COFFEE BEANS BAG 5 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_124",
    "code": "10011002",
    "name_ar": "قهوة دانكن مطحونة (كيس 1 رطل)",
    "name_en": "COFFEE.DD COFFEE GROUNDS BAG 01 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_125",
    "code": "10011003",
    "name_ar": "حبوب قهوة دانكن دارك روست كاملة (كيس 2 رطل)",
    "name_en": "COFFEE.DD DARK ROAST WHOLE BEAN BAG 02 LBS",
    "category": "قهوة وكبسولات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_126",
    "code": "15021006",
    "name_ar": "بنطلون زي موحد مقاس 34",
    "name_en": "UNIFORM PANTS 34",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_127",
    "code": "15021007",
    "name_ar": "بنطلون زي موحد مقاس 36",
    "name_en": "UNIFORM PANTS 36",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_128",
    "code": "13014001",
    "name_ar": "أكياس ورقية بنية 5 أرطال (1 × 1000 حبة)",
    "name_en": "BAGS.BAG BROWN 5 LBS (1X1000 PCS)",
    "category": "أكياس التعبئة والتسوق",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_129",
    "code": "13012010",
    "name_ar": "صندوق بوكس أوف جو دانكن 112 أونصة",
    "name_en": "BOXES.BOX O JOE (DUNKIN BOX 112 OZ)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_130",
    "code": "13012019",
    "name_ar": "صندوق بوكس أوف جو دانكن 20 أونصة",
    "name_en": "BOXES.BOX O JOE(DUNKIN BOX 20OZ)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_131",
    "code": "13012018",
    "name_ar": "صندوق بوكس أوف جو دانكن 40 أونصة",
    "name_en": "BOXES.BOX O JOE(DUNKIN BOX 40OZ)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_132",
    "code": "13012020",
    "name_ar": "صندوق بوكس أوف جو دانكن برتقالي 40 أونصة",
    "name_en": "BOXES.BOX O JOE(ORANGE BOX 40OZ)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_133",
    "code": "13012007",
    "name_ar": "علبة دونات 3 حبات للسعودية",
    "name_en": "BOXES.BOX OF 3 FOR KSA",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_134",
    "code": "13012006",
    "name_ar": "مقسم علبة دونات 12 حبة",
    "name_en": "BOXES.DIVIDER 12PCS FOR DONUT BOX 12PCS",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_135",
    "code": "13012005",
    "name_ar": "مقسم علبة دونات 6 حبات",
    "name_en": "BOXES.DIVIDER 6PCS FOR DONUT BOX 6PCS",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_136",
    "code": "13012001",
    "name_ar": "علبة دونات 6 حبات",
    "name_en": "BOXES.DONUT BOX 6 PCS",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_137",
    "code": "13012002",
    "name_ar": "علبة دونات مطبوعة 12 حبة",
    "name_en": "BOXES.DONUT BOX PRINTED 12 PCS",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_138",
    "code": "13012003",
    "name_ar": "علبة مونشكين سعة 25 حبة",
    "name_en": "BOXES.MUNCHKIN BOX OF 25",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_139",
    "code": "13011004",
    "name_ar": "أكواب قهوة وشاي 10 أونصة",
    "name_en": "CUPS COFFEE AND TEA CUPS 10OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_140",
    "code": "13011011",
    "name_ar": "أكواب قهوة وشاي مزدوجة الجدار 10 أونصة",
    "name_en": "CUPS DW COFFEE AND TEA CUPS 10OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_141",
    "code": "13011012",
    "name_ar": "أكواب قهوة وشاي مزدوجة الجدار 14 أونصة",
    "name_en": "CUPS DW COFFEE AND TEA CUPS 14OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_142",
    "code": "13011014",
    "name_ar": "أكواب قهوة وشاي مزدوجة الجدار 16 أونصة",
    "name_en": "CUPS DW COFFEE AND TEA CUPS 16OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_143",
    "code": "13011015",
    "name_ar": "أكواب قهوة وشاي مزدوجة الجدار 20 أونصة",
    "name_en": "CUPS DW COFFEE AND TEA CUPS 20OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_144",
    "code": "13011013",
    "name_ar": "أكواب قهوة وشاي مزدوجة الجدار 9 أونصة",
    "name_en": "CUPS DW COFFEE AND TEA CUPS 9OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_145",
    "code": "13011006",
    "name_ar": "أكواب قهوة أحادية الجدار 16 أونصة",
    "name_en": "CUPS.COFFEE CUPS 16OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_146",
    "code": "13011007",
    "name_ar": "أكواب قهوة أحادية الجدار 20 أونصة",
    "name_en": "CUPS.COFFEE CUPS 20OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_147",
    "code": "13011008",
    "name_ar": "أكواب قهوة أحادية الجدار 9 أونصة",
    "name_en": "CUPS.COFFEE CUPS 9OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_148",
    "code": "13011016",
    "name_ar": "أكواب كابتشينو مزدوجة الجدار 10 أونصة",
    "name_en": "CUPS.D/W CAPPUCCINO CUP 10OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_149",
    "code": "13011019",
    "name_ar": "أكواب كابتشينو مزدوجة الجدار 12 أونصة",
    "name_en": "CUPS.D/W CAPPUCCINO CUP 12OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_150",
    "code": "13011017",
    "name_ar": "أكواب كابتشينو مزدوجة الجدار 16 أونصة",
    "name_en": "CUPS.D/W CAPPUCCINO CUP 16 OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_151",
    "code": "13011018",
    "name_ar": "أكواب كابتشينو مزدوجة الجدار 20 أونصة",
    "name_en": "CUPS.D/W CAPPUCCINO CUP 20 OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_152",
    "code": "13011010",
    "name_ar": "أكواب إسبريسو 4 أونصة",
    "name_en": "CUPS.ESPRESSO CUPS 4OZ",
    "category": "أكواب ساخنة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_153",
    "code": "13023002",
    "name_ar": "أكياس تسوق دانكن كبيرة",
    "name_en": "BAGS.DD SHOPPING BAGS LARGE",
    "category": "أكياس التعبئة والتسوق",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_154",
    "code": "13023003",
    "name_ar": "أكياس تسوق دانكن صغيرة",
    "name_en": "BAGS.DD SHOPPING BAGS SMALL",
    "category": "أكياس التعبئة والتسوق",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_155",
    "code": "13021005",
    "name_ar": "أكواب باردة شفافة بلاستيك 12 أونصة",
    "name_en": "CUPS.COLD CUP CLEAR PLASTIC - 12 OZ",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_156",
    "code": "13021001",
    "name_ar": "أكواب باردة بلاستيك 4 أونصة",
    "name_en": "CUPS.COLD CUPS 4OZ",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_157",
    "code": "13021002",
    "name_ar": "أكواب باردة بلاستيك 16 أونصة",
    "name_en": "CUPS.COLD CUPS PLASTIC 16OZ",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_158",
    "code": "13021003",
    "name_ar": "أكواب باردة بلاستيك 24 أونصة",
    "name_en": "CUPS.COLD CUPS PLASTIC 24OZ",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_159",
    "code": "13021006",
    "name_ar": "أكواب باردة بلاستيك 32 أونصة",
    "name_en": "CUPS.COLD CUPS PLASTIC 32OZ",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_160",
    "code": "13021004",
    "name_ar": "أكواب بلاستيكية للعينات / البورشن (مغلف 50 حبة)",
    "name_en": "CUPS.PORTION PLASTIC CUPS SLEEVE (1X50 PCS)",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_161",
    "code": "13021021",
    "name_ar": "علب صوص بلاستيك 2 أونصة (20 مغلف × 100 حبة)",
    "name_en": "SAUCE CUP 2 OZ 20 PACK X 100 PCS",
    "category": "الأكواب الباردة",
    "mode": "detailed",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_162",
    "code": "10092001",
    "name_ar": "مرتديلا دجاج (مغلف 5 حبات)",
    "name_en": "MORTADELLA.CHICKEN MORTADELLA",
    "category": "دواجن ولحوم",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_163",
    "code": "10092018",
    "name_ar": "بيض مجمد للساندوتش 1 كجم",
    "name_en": "SANDWICH FROZEN EGG 1KG",
    "category": "دواجن ولحوم",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_164",
    "code": "10092002",
    "name_ar": "بيض سائل مبستر مبرد للساندوتش 1 كجم",
    "name_en": "SANDWICH.LIQUID WHOLE EGG CHILLED PAST 1KG",
    "category": "دواجن ولحوم",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_165",
    "code": "12011052",
    "name_ar": "دونات لوز وبندق",
    "name_en": "ALMOND HAZELNUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_166",
    "code": "12011034",
    "name_ar": "دونات بوستون كريم",
    "name_en": "BOSTON CREAM DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_167",
    "code": "12011100",
    "name_ar": "دونات شوكو كوكو",
    "name_en": "CHOCO COCO DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_168",
    "code": "12011001",
    "name_ar": "دونات شوكولاتة فروستد",
    "name_en": "CHOCO FROSTED DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_169",
    "code": "12011006",
    "name_ar": "دونات شوكولاتة سبرنكلز",
    "name_en": "CHOCO SPRINKLE",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_170",
    "code": "12011085",
    "name_ar": "دونات كولد برو كرانش",
    "name_en": "COLD BREW CRUNCH DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_171",
    "code": "12011088",
    "name_ar": "دونات كوكيز",
    "name_en": "COOKIE DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_172",
    "code": "12011069",
    "name_ar": "دونات كوكيز آند كريم ماربل",
    "name_en": "COOKIES AND CREAM MARBLE",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_173",
    "code": "12011082",
    "name_ar": "دونات كوتن كاندي بف",
    "name_en": "COTTON CANDY PUFF",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_174",
    "code": "12011002",
    "name_ar": "دونات جليزد سادة",
    "name_en": "GLAZED DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_175",
    "code": "12011098",
    "name_ar": "دونات كنافة شوكو كرانش",
    "name_en": "KUNAFA CHOCO CRUNCH",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_176",
    "code": "12011064",
    "name_ar": "دونات لونج جون",
    "name_en": "LONG JOHN",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_177",
    "code": "12011094",
    "name_ar": "ميني دونات شوكو فروست",
    "name_en": "MINI CHOCO FROST",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_178",
    "code": "12011096",
    "name_ar": "ميني دونات كريمة التمر",
    "name_en": "MINI DATES CREAM",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_179",
    "code": "12011067",
    "name_ar": "دونات أولد فاشوند",
    "name_en": "OLD FASHIONED DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_180",
    "code": "12011099",
    "name_ar": "دونات بينك بيري",
    "name_en": "PINK BERRY",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_181",
    "code": "12011092",
    "name_ar": "دونات بيربل فلفيت كريم",
    "name_en": "PURPLE VELVET CREAM",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_182",
    "code": "12011093",
    "name_ar": "دونات بيربل فلفيت سبرنكل",
    "name_en": "PURPLE VELVET SPRINKLE",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_183",
    "code": "12011101",
    "name_ar": "دونات تشيزكيك الفراولة كرانش",
    "name_en": "STRAWBERRY CHEESECAKE CRUNCH",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_184",
    "code": "12011044",
    "name_ar": "دونات تشيزكيك الفراولة",
    "name_en": "STRAWBERRY CHESSECAKE",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_185",
    "code": "12011056",
    "name_ar": "دونات تيراميسو تشيزكيك",
    "name_en": "TIRAMISU CHEESECAKE",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_186",
    "code": "12011087",
    "name_ar": "دونات فانيليا كاندي سبرنكل",
    "name_en": "VANILLA CANDY SPRINKLE DONUT",
    "category": "مونشكين ودونات عادي",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_187",
    "code": "14022002",
    "name_ar": "جل معقم لليدين (زجاجة)",
    "name_en": "CHEMICALS.HAND SANITIZING GEL BOTTLE",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_188",
    "code": "14022003",
    "name_ar": "أقراص معقم إيكولاب كاي 5 (علبة 240 قرص)",
    "name_en": "ECOLAB KAY 5 SANITIZER TABLET 1 BOX (240 TABLETS)",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_189",
    "code": "10061045",
    "name_ar": "كوكيز قطع الشوكولاتة",
    "name_en": "CHOCO CHIP COOKIES",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_190",
    "code": "10061017",
    "name_ar": "صوص زعفران (4 × 1.89 لتر)",
    "name_en": "SAFFRON SAUCE (4 X 1.89 LTR)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_191",
    "code": "10061002",
    "name_ar": "صوص أرابيسكي كراميل مملح 3 كجم للفرابيه",
    "name_en": "SAUCE.ARABESCHI CARAMEL FLEUR DE SEL 3 KG FOR FRAPPE",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_192",
    "code": "10061004",
    "name_ar": "صوص أرابيسكي فراولة إكسترا 1 كجم",
    "name_en": "SAUCE.ARABESCHI STRAWBERRY EXTRA 1 KG",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_193",
    "code": "10061016",
    "name_ar": "صوص شيبوتلي مايونيز 225 مل",
    "name_en": "SAUCE.CHIPOTLE MAYONNAISE 225ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_194",
    "code": "10061011",
    "name_ar": "صوص بنكهة الشوكولاتة 2 لتر",
    "name_en": "SAUCE.CHOCOLATE FLAVORED SAUCE (2 LTR)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_195",
    "code": "10061010",
    "name_ar": "صوص كراميل مملح دا فينشي 2 لتر للاتيه",
    "name_en": "SAUCE.DA VINCI SALTED CARAMEL SAUCE 2LTR FOR LATTE",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_196",
    "code": "10061019",
    "name_ar": "صوص دا فينشي جورميه بنكهة القهوة العربية (3 × 2 لتر)",
    "name_en": "SAUCE.DAVINCI GOURMET ARABIC COFFEE FLAVORED SAUCE (3PX2L)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_197",
    "code": "10061012",
    "name_ar": "صوص ليمونادة 1 لتر",
    "name_en": "SAUCE.LEMONADE 1 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_198",
    "code": "10061007",
    "name_ar": "صوص مايونيز كريمي 400 مل",
    "name_en": "SAUCE.MAYONNAISE CREAMY 400ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_199",
    "code": "10061006",
    "name_ar": "صوص كاتشب طماطم 570 مل",
    "name_en": "SAUCE.TOMATO KETCHUP 570ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_200",
    "code": "10061013",
    "name_ar": "صوص بطيخ 750 مل",
    "name_en": "SAUCE.WATERMELON 750ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_201",
    "code": "10061005",
    "name_ar": "صوص شوكولاتة بيضاء 2 لتر",
    "name_en": "SAUCE.WHITE CHOCOLATE SAUCE 2 LTR",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_202",
    "code": "10061018",
    "name_ar": "صوص بيستو 185 جم",
    "name_en": "SPREADS.PESTO SAUCE 185 GM",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_203",
    "code": "10061001",
    "name_ar": "صوص تاباسكو سيراتشا (300 جم)",
    "name_en": "TABASCO SRIRACHA SAUCE (300 GRM)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_204",
    "code": "10063002",
    "name_ar": "عسل طبيعي 380 جم",
    "name_en": "SPREADS.HONEY 380 GM",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_205",
    "code": "14021004",
    "name_ar": "صابون غسيل أيدي كاي 4 جالون",
    "name_en": "CHEMICALS.KAY QSR AMH HAND WASH 4 GALLON",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_206",
    "code": "14021003",
    "name_ar": "صابون يدين نافكير 1 لتر",
    "name_en": "CHEMICALS.NAPHCARE-HAND SOAP 1 LTR",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_207",
    "code": "14021001",
    "name_ar": "منظف متعدد الاستخدامات إيكولاب كاي (علبة 168 ظرف)",
    "name_en": "ECOLAB CHEMICALS.KAY MULTI PURPOSE 1 BOX (168 SACHETS)",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_208",
    "code": "99021099",
    "name_ar": "كبسولات نيتروجين N2O للكريمة ISI (علبة 10 حبات)",
    "name_en": "ISI N2O CREAM CHARGER IS-0703 (BOX-10PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_209",
    "code": "99021027",
    "name_ar": "جهاز موزع مناديل ماكسي رول",
    "name_en": "MAXI ROLL DISPENSER",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_210",
    "code": "99021023",
    "name_ar": "جهاز موزع صابون",
    "name_en": "SOAP DISPENSER",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_211",
    "code": "13025002",
    "name_ar": "شفاطات بلاستيكية كبيرة (مغلف 1 × 100 حبة)",
    "name_en": "DISPOSABLES.PLASTIC STRAW BIG (1X100 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_212",
    "code": "13025001",
    "name_ar": "شفاطات بلاستيكية صغيرة (مغلف 1 × 250 حبة)",
    "name_en": "DISPOSABLES.PLASTIC STRAW SMALL (1X250 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_213",
    "code": "10141003",
    "name_ar": "أصابع سكر بني (1 × 2000 حبة)",
    "name_en": "SUGAR.BROWN SUGAR STICK (1X2000)",
    "category": "السكر والمحليات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_214",
    "code": "10141002",
    "name_ar": "أصابع سكر أبيض 5 جم (1 × 2000 حبة)",
    "name_en": "SUGAR.SUGAR STICK 5GM (1X2000)",
    "category": "السكر والمحليات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_215",
    "code": "10141004",
    "name_ar": "سكر دايت تروبيكانا سليم (1 × 1200 ظرف)",
    "name_en": "SUGAR.TROPICANA SLIM SUGAR (1X1200)",
    "category": "السكر والمحليات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_216",
    "code": "10081001",
    "name_ar": "شراب قصب السكر 750 مل",
    "name_en": "SYRUP.SUGAR CANE SYRUP 750 ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_217",
    "code": "10131001",
    "name_ar": "شاي أسود بولد بريكفاست (15 كيس / علبة)",
    "name_en": "TEA.BOLDBREAKFAST BLACK TEA (1X15 /BOX)",
    "category": "شاي ومشروبات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_218",
    "code": "10131002",
    "name_ar": "شاي كرك 500 جم",
    "name_en": "TEA.KARAK CHAI 500GM",
    "category": "شاي ومشروبات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_219",
    "code": "14028001",
    "name_ar": "شرائط اختبار الكلور إيكولاب كاي",
    "name_en": "ECOLAB CHEMICALS.KAY CHLORINE TEST STRIPS",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_220",
    "code": "10122001",
    "name_ar": "توست تكساس دانكن (1 × 100 حبة)",
    "name_en": "SANDWICH.DD TOAST TEXAS (1X100 PCS)",
    "category": "مخبوزات وساندوتشات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_221",
    "code": "15011012",
    "name_ar": "تي شيرت بائع مقاس (L)",
    "name_en": "UNIFORM.SALESMAN T-SHIRT (L)",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_222",
    "code": "15011014",
    "name_ar": "تي شيرت بائع مقاس (M)",
    "name_en": "UNIFORM.SALESMAN T-SHIRT(M)",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_223",
    "code": "12051001",
    "name_ar": "زجاجة بلوتوث سوداء 500 مل",
    "name_en": "BLUETOOTH BOTTLEBLACK 500ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_224",
    "code": "12051002",
    "name_ar": "زجاجة بلوتوث برتقالية 500 مل",
    "name_en": "BLUETOOTH BOTTLEORANGE 500ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_225",
    "code": "12051003",
    "name_ar": "كوب حافظ حرارة بلوتوث أسود 800 مل",
    "name_en": "BLUETOOTH TUMBLERBLACK 800ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_226",
    "code": "12051004",
    "name_ar": "كوب حافظ حرارة بلوتوث أبيض 800 مل",
    "name_en": "BLUETOOTH TUMBLERWHITE 800ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_227",
    "code": "12051008",
    "name_ar": "مطارة ماء رياضية سيليكون برتقالية 2 لتر",
    "name_en": "GYM SILICON L ORANGE 2LTR",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_228",
    "code": "12051006",
    "name_ar": "مطارة ماء رياضية سيليكون بيضاء 600 مل",
    "name_en": "GYM SILICON R WHITE 600ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_229",
    "code": "12051014",
    "name_ar": "ماج حافظ للحرارة مفرغ من الهواء 480 مل",
    "name_en": "MERCHANDISE.VACUUM MUG 480ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_230",
    "code": "12051012",
    "name_ar": "كوب بيلموا بريميوم برتقالي 473 مل",
    "name_en": "PILMOA PREMIUM ORANGE 473ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_231",
    "code": "12051011",
    "name_ar": "كوب بيلموا بريميوم ستانلس ستيل 473 مل",
    "name_en": "PILMOA PREMIUM SUS 473ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_232",
    "code": "12051010",
    "name_ar": "كوب بيلموا بريميوم أبيض 473 مل",
    "name_en": "PILMOA PREMIUM WHITE 473ML",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_233",
    "code": "12051040",
    "name_ar": "تملبر شوكولار دانكن أسود",
    "name_en": "TUMBLER.CHOCOLAR TUMBLER DD - BLACK",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_234",
    "code": "12051052",
    "name_ar": "كوب دانكن الجديد العادي",
    "name_en": "TUMBLER.NEW DUNKIN MUG REGULAR",
    "category": "أكواب وتملبرات مبيعات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_235",
    "code": "12041004",
    "name_ar": "مياه إيفيان فوارة علب 24 × 0.33 لتر",
    "name_en": "EVIAN SPARKLING WATER CAN 24 X 0.33L",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_236",
    "code": "12041005",
    "name_ar": "مياه كينزا فوارة زجاجة 250 مل",
    "name_en": "KINZA-SPARKLING WATER BOTTLE 250ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_237",
    "code": "12041002",
    "name_ar": "مياه إيفيان زجاجة 500 مل",
    "name_en": "WATER.EVIAN WATER BOTTLE 500 ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_238",
    "code": "12041003",
    "name_ar": "مياه نوفا زجاجة 330 مل",
    "name_en": "WATER.NOVA WATER BOTTLE 330 ML",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_239",
    "code": "14012001",
    "name_ar": "ممسحة أرضيات",
    "name_en": "DISPOSABLES.FLOOR WIPER",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_240",
    "code": "13051001",
    "name_ar": "أعواد تحريك خشبية (1 × 1000 حبة)",
    "name_en": "DISPOSABLES.STIR STICKS (1X1000 PCS)",
    "category": "مستلزمات ونظافة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PKT - باكيت",
    "unit_code": "PKT",
    "unit_label": "باكيت (PKT)"
  },
  {
    "id": "prod_241",
    "code": "13013001",
    "name_ar": "أكياس تغليف ساندوتش ورقية (1 × 2000 حبة)",
    "name_en": "BAGS.WRAP SANDWICH BAG (1X2000 PCS)",
    "category": "أكياس التعبئة والتسوق",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_242",
    "code": "10083056",
    "name_ar": "شراب ليمونادة يالوفا (كرتون × 6 حبات × 750 مل)",
    "name_en": "LEMONADE SYRUP YALOVA (CTN x 6 PCS x 750 ML)",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_243",
    "code": "10131011",
    "name_ar": "شاي كركديه (كرتون × 24 حبة × 250 جم)",
    "name_en": "HIBISCUS TEA (CTN X 24 PCS X 250 GRM)",
    "category": "شاي ومشروبات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "CTN - كرتون",
    "unit_code": "CTN",
    "unit_label": "كرتون (CTN)"
  },
  {
    "id": "prod_244",
    "code": "10082003",
    "name_ar": "شراب (سيروب) بطيخ 750 مل",
    "name_en": "WATERMELON SYRUP 750ML",
    "category": "الشرابات والصلصات والبودرة",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_245",
    "code": "14021008",
    "name_ar": "دايفرسي - رغوة عناية ناعمة لليدين H42",
    "name_en": "DIVERSEY-SOFT CARE FOAM H42",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_246",
    "code": "14022009",
    "name_ar": "دايفرسي - معقم عناية ناعمة E H5 (5 لتر)",
    "name_en": "DIVERSEY-SOFTCARE DES E H5 5LITER",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_247",
    "code": "14024003",
    "name_ar": "دايفرسي - سوما مزيل تكلسات D5",
    "name_en": "DIVERSEY-SUMA CAL-X D5 5",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_248",
    "code": "14022010",
    "name_ar": "دايفرسي - سوما منظف شوايات للحرارة العالية D9.8",
    "name_en": "DIVERSEY-SUMA GRILL HI-TEMP D9.8 750ML",
    "category": "المنظفات والمعقمات",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_249",
    "code": "13012062",
    "name_ar": "صندوق دريم دونات سكويشيز 10 حبات",
    "name_en": "DREAM DONUT BOX SQUISHIES 10 PCS (CTN x 200 Pcs)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_250",
    "code": "13012063",
    "name_ar": "صندوق دريم دونات سكويشيز 20 حبة",
    "name_en": "DREAM DONUT BOX SQUISHIES 20 PCS (CTN x 100 Pcs)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_251",
    "code": "13012064",
    "name_ar": "مقسم دريم دونات سكويشيز 10 حبات",
    "name_en": "DREAM DONUT DIVIDER SQUISHIES 10 PCS(CTN x 200 PCS)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_252",
    "code": "13012065",
    "name_ar": "مقسم دريم دونات سكويشيز 20 حبة",
    "name_en": "DREAM DONUT DIVIDER SQUISHIES 20 PCS(CTN x 100 Pcs)",
    "category": "الصناديق والعلب",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_253",
    "code": "15011067",
    "name_ar": "زي موحد - تي شيرت مدرب مقاس (L)",
    "name_en": "UNIFORM.TRAINER T-SHIRT - L",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_254",
    "code": "15011068",
    "name_ar": "زي موحد - تي شيرت مدرب مقاس (XL)",
    "name_en": "UNIFORM.TRAINER T-SHIRT - XL",
    "category": "زي الموظفين (Uniform)",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  },
  {
    "id": "prod_255",
    "code": "12041001",
    "name_ar": "جالون مياه 18.9 لتر",
    "name_en": "WATER.GALLON WATER",
    "category": "مياه وعصائر",
    "mode": "simple",
    "qty": "",
    "packs": "",
    "pack_size": "",
    "loose": "",
    "unit": "PCS - حبة",
    "unit_code": "PCS",
    "unit_label": "حبة (PCS)"
  }
] as const;
